### ISSUE TITLE
Questions about data type and band

### ISSUE THREAD

**Issue by JXMss** [venkatesh-thiru/Deep-Harmonization#1]
I have some questions about the model:
1. Can we use (and only use)  sentinel-2 as the input data? I noticed that in your paper, this model seems to use L8 as input data, correct?

2. What is the correct channel order of the input data? this model accept 7 channels, but I haven't found any specific band order on GitHub page or in the paper, and I noticed that l8 data has 7 bands, is this means this model can only use l8 data?

3. Is there any method that I can apply it on sentinel-2 data?

Thank you very much for providing the pre-trained model and working.

**Comment by venkatesh-thiru** [comment]
1) Yes, the model is explicitly trained to upsample Landsat images. It is trained on Landsat-8 images but generalizes well to Landsat-9 images.

2) Thank you for pointing this out. The multi-spectral channel order is as follows:
```"bands" : ['blue', 'green', 'red', 'nir08', 'swir16', 'swir22']```, 
The band names are the same as what you get from USGS's STAC server: ```https://landsatlook.usgs.gov/stac-server```
We concatenate the respective pan-chromatic inputs as the final channel. I have now fixed this info on the readme

3) As mentioned before, this framework is explicitly designed to upscale Landsat images to Sentinel-2's resolution. We could fine-tune these models if we obtain images with a finer resolution compared to Sentinel-2. However, the existing pre-trained models are not trained for such resolutions.
